# These are sequences found in NC_045512.2.fasta marking the start and end of the S1 and
# S2 domains.

S1_PREFIX = "CAGTGTGTTAATCTTACAACCAGAACTCAATTACCCCCTG"
S1_SUFFIX = "TAGTTATCAGACTCAGACTAATTCTCCTCGGCGGGCACGT"

S2_PREFIX = "AGTGTAGCTAGTCAATCCATCATTGCCTACACTATGTCAC"
S2_SUFFIX = "CTCTGAGCCAGTGCTCAAAGGAGTCAAATTACATTACACA"
